# Example API Keys Configuration
# Copy this to api_keys.yaml and add your actual API keys
# Note: api_keys.yaml is ignored by git for security

# OpenAI Configuration
openai:
  api_key: "your_openai_api_key_here"
  organization: ""  # Optional

# Anthropic Configuration
anthropic:
  api_key: "your_anthropic_api_key_here"

# Alternative: Use environment variables
# Set OPENAI_API_KEY and ANTHROPIC_API_KEY in your environment
# and leave the above values empty